<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Run_tryitLeaderboard</name>
   <tag></tag>
   <elementGuidId>61ca15d2-3e72-462f-9971-1ba85edb1fd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tryitLeaderboard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tryitLeaderboard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tryitLeaderboard</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8b4367a-7817-4fd3-84a6-c1bfd6b212f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tryitLeaderboard</value>
      <webElementGuid>feb830da-1142-4c6b-b1bb-32834908adb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tryitLeaderboard&quot;)</value>
      <webElementGuid>c243cb0d-a62f-4f23-9db4-6d86ab133cb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tryitLeaderboard']</value>
      <webElementGuid>1da73938-dae4-4c16-9714-6047dbf54d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Run ❯'])[1]/preceding::div[3]</value>
      <webElementGuid>ee0bfe2f-4bb3-4d04-8d3c-9c2b9932fe64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>e8013338-f835-4887-bab4-f3d3382caeca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tryitLeaderboard']</value>
      <webElementGuid>7b655800-cb44-4786-a2d2-98f048b26a86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
